version: "3.8"

services:
  openapi_mock:
    image: muonsoft/openapi-mock
    volumes:
    - ./apps/api/api.yaml:/etc/api/api.yaml
    environment:
      OPENAPI_MOCK_SPECIFICATION_URL: "/etc/api/api.yaml"
      OPENAPI_MOCK_NULL_PROBABILITY: 0
      OPENAPI_MOCK_CORS_ENABLED: true
    ports:
      - "9999:8080"
